const anteriorLidsOptions = [
  'Normal',
  'MGD',
  'Anterior blepharitis',
  'Bell\'s phenomenon',
  'Blepharophimosis',
  'Chalazion',
  'Coloboma',
  'Cyst',
  'Deep socket',
  'Dermatochalasis',
  'Ecchymosis',
  'Ectropion',
  'Edema',
  'Entropion',
  'Floppy eyelids',
  'Hordeolum externum (stye)',
  'Hordeolum internum',
  'Laceration',
  'Lagophthalmos',
  'Lashes',
  'Lid lag',
  'Lid laceration',
  'Matted lashes',
  'Pigmented lesion',
  'Pthriasis palpebrarum',
  'Ptosis',
  'Scar',
  'Skin',
  'Tumor',
  'Xanthelasma',
  'Other',
];
