class AnteriorSection {
  const AnteriorSection({
    required this.key,
    required this.label,
    required this.options,
  });

  final String key;
  final String label;
  final List<String> options;
}

const anteriorLidsOptions = [
  'Normal',
  'MGD',
  'Anterior blepharitis',
  "Bell's phenomenon",
  'Blepharophimosis',
  'Chalazion',
  'Coloboma',
  'Cyst',
  'Deep socket',
  'Dermatochalasis',
  'Ecchymosis',
  'Ectropion',
  'Edema',
  'Entropion',
  'Floppy eyelids',
  'Hordeolum externum (stye)',
  'Hordeolum internum',
  'Laceration',
  'Lagophthalmos',
  'Lashes',
  'Lid lag',
  'Lid laceration',
  'Matted lashes',
  'Pigmented lesion',
  'Pthriasis palpebrarum',
  'Ptosis',
  'Scar',
  'Skin',
  'Tumor',
  'Xanthelasma',
  'Other',
];

const anteriorConjunctivaOptions = [
  "Bitot's spot",
  'Bleb',
  'Chemosis',
  'Concretions',
  'Congestion',
  'Conjunctivochalasis',
  'Corneo-scleral wound',
  'Cyst',
  'Discharge',
  'Episcleritis',
  'Follicles',
  'Foreign Body',
  'GDD',
  'Haemorrhage',
  'Limbal hyperplasia',
  'Limbal papillae',
  'Maggots',
  'Membranes',
  'Muddy',
  'Naevus',
  'Nodules',
  'Normal',
  'Papillae',
  'Phlycten',
  'Pigmentation',
  'Pinguecula',
  'Pterygium',
  'Releasable suture',
  'Scarring',
  'Scleral laceration',
  'Scleral melting',
  'Scleral Necrosis',
  'Scleral thinning',
  'Subconjunctival haemorrhage',
  'Symblepharon',
  'Tear',
  'Warts',
  'Other',
];

const anteriorCorneaOptions = [
  'Abrasion',
  'Arcus Senilis',
  'Band shaped keratopathy',
  'Blood staining of endothelium',
  'Bullae',
  'Bullous keratopathy',
  'Clear',
  'Conjunctivalisation',
  'Degeneration',
  'Dendrite',
  'Deposits',
  'Descemetocele',
  'DMD',
  'DM folds',
  'DM loss',
  'DM stripping',
  'Dystrophy',
  'Edema',
  'Endothelial dusting',
  'Epithelial Defect',
  'Filaments',
  'Fleischer ring',
  'Foreign body',
  'Ghost vessels',
  'Graft',
  'Guttae',
  'Hazy',
  'Infiltrate',
  'Keratic precipitates',
  'Keratoconus',
  'Krukenberg spindle',
  'Megalocornea',
  'Microcornea',
  'Opacity',
  'Pannus',
  'Pigments on Endothelium',
  'Prominent corneal nerves',
  'Pseudodendrite',
  'Pseudo cornea',
  'Pseudoexfoliation on Endothelium',
  'Punctate epithelial erosions',
  'Punctate Epithelial Keratitis',
  'Punctate epithelial keratitis',
  'Sensation',
  'Spheroidal degeneration',
  'Staphyloma',
  'Sub-epithelial infiltrates',
  'Superficial punctate keratitis',
  'Tear',
  'Thinning',
  'Ulcer',
  'Vascularisation',
  'Vogt Striae',
  'Other',
];

const anteriorChamberOptions = [
  'ACIOL',
  'Blood clot',
  'Cells (descriptive option)',
  'Depth (descriptive option)',
  'Exudates',
  'Flare (descriptive option)',
  'Foreign body',
  'Granuloma',
  'Haptic of PCIOL in AC',
  'Hyphema (descriptive option)',
  'Hypopyon (descriptive option)',
  'Lens matter in AC',
  'Normal Depth',
  'Pigment',
  'Quiet',
  'Shallow',
  'Vitreous in AC',
  'Other',
];

const anteriorIrisOptions = [
  'Aniridia',
  'Anterior synechiae',
  'Atrophy',
  'Coloboma',
  'Color (descriptive option)',
  'Cyst',
  'Foreign body',
  'Hole',
  'Iridodialysis',
  'Iridodonesis',
  'Multiple sphincterotomy',
  'Neovascularization',
  'Nodules',
  'Normal colour and pattern',
  'Peripheral Anterior Synechiae',
  'Peripheral Iridectomy',
  'Posterior Synechiae',
  'Pseudoexfoliation',
  'Sector Iridectomy',
  'Sphincter Tear',
  'Transillumination Defect',
  'Other',
];

const anteriorPupilOptions = [
  'AAPD- Absolute afferent pupillary defect',
  'Normal size and reaction to light',
  'Optic capture',
  'Pharmacologically dilated',
  'PXF',
  'RAPD',
  'Reaction to light (Descriptive option)',
  'Shape (descriptive option)',
  'Size (Descriptive option)',
  'Sphincter atrophy',
  'Sphincter Tear',
  'Traumatic mydriasis',
  'Other',
];

const anteriorLensOptions = [
  'ACIOL',
  'Anterior Capsular Fibrosis',
  'Aphakia',
  'Brown Cataract',
  'Cataract',
  'Cortical cataract',
  'Clear',
  'Dislocated IOL',
  'Ectopia lens',
  'Foreign body',
  'IOL',
  'Lens changes',
  'Mature Cataract',
  'No Phacodonesis',
  'Nuclear Sclerosis (Descriptive option)',
  'PSCC',
  'PCIOL',
  'PCO',
  'Phacodonesis',
  'Pigments on ALC',
  'PPC',
  'PXF on ALC',
  'Subluxated lens',
  'YAG opening',
  'Other',
];

const anteriorOcularMovementsOptions = [
  'Full and free',
  'Limitation (Descriptive option)',
  'Restricted',
  'Nystagmus',
  'Pursuits',
  'Saccades',
  'Other',
];

const anteriorCornealReflexOptions = [
  'Esotropia',
  'Exotropia',
  'Hypertropia',
  'Hypotropia',
  'Normal',
  'Other',
];

const anteriorGlobeOptions = [
  'Absent',
  'Absolute Glaucoma',
  'Anophthalmos',
  'Artificial prosthesis',
  'Cystic eyeball',
  'Microphthalmos',
  'Normal',
  'One eyed',
  'Other',
];

const anteriorSegmentSections = [
  AnteriorSection(
    key: 'lids',
    label: 'Lids',
    options: anteriorLidsOptions,
  ),
  AnteriorSection(
    key: 'conjunctiva',
    label: 'Conjunctiva',
    options: anteriorConjunctivaOptions,
  ),
  AnteriorSection(
    key: 'cornea',
    label: 'Cornea',
    options: anteriorCorneaOptions,
  ),
  AnteriorSection(
    key: 'anterior_chamber',
    label: 'Anterior Chamber',
    options: anteriorChamberOptions,
  ),
  AnteriorSection(
    key: 'iris',
    label: 'Iris',
    options: anteriorIrisOptions,
  ),
  AnteriorSection(
    key: 'pupil',
    label: 'Pupil',
    options: anteriorPupilOptions,
  ),
  AnteriorSection(
    key: 'lens',
    label: 'Lens',
    options: anteriorLensOptions,
  ),
  AnteriorSection(
    key: 'ocular_movements',
    label: 'Ocular movements',
    options: anteriorOcularMovementsOptions,
  ),
  AnteriorSection(
    key: 'corneal_reflex',
    label: 'Corneal reflex',
    options: anteriorCornealReflexOptions,
  ),
  AnteriorSection(
    key: 'globe',
    label: 'Globe',
    options: anteriorGlobeOptions,
  ),
];
