const diagnosisOptions = [
  'ERM-Epiretinal membrane',
  'Preretinal haemorrhage',
  'ARN-Acute retinal necrosis',
  'TRD-Tractional retinal detachment',
  'RRD-Rhegmatogenous retinal detachment',
  'ROP-Retinopathy of prematurity',
  'RAP - retinal angiomatous proliferation',
  'RP-Retinitis pigmentosa',
  'Myopic chorioretinal atrophy',
  'Retinal operculated tear',
  'Snail-track retinal degeneration',
  'Retinal hole',
  'BRVO - Branch retinal vein occlusion',
  'Retinal scar',
  'Thrombophlebitis of retinal vein',
  'Gross myopic retinal degeneration',
  'NVG-Neovascular glaucoma',
  'BRAO - Branch retinal artery occlusion',
  'PDR-Proliferative diabetic retinopathy',
  'CSR-Central serous retinopathy',
  'Helicoid peripapillary chorioretinal degeneration',
  'Sensory retinal dystrophy',
  'Central retinal artery occlusion',
  'Retinal linear tear',
  'Geographic retinal dysplasia',
  'Macular branch retinal vein occlusion',
  'CRVO-Central retinal vein occlusion',
  'Subretinal hemorrhage',
  'CME-Cystoid macular edema',
  'Retinal U shaped tear',
  'CRAO - Central retinal artery occlusion',
  'GRT-Giant retinal tear',
  'Retinoschisis and retinal cysts',
  'Subretinal disciform lesion',
  'Macular subretinal hemorrhage',
  'Total retinal detachment',
  'Chorioretinal scar',
  'Vitreoretinal lymphoma',
  'Cilioretinal artery occlusion',
  'Retinal dialysis',
  'Retinal vasculitis',
  'Hereditary dominant drusen retinal dystrophy',
  'Snowflake retinal degeneration',
  'VH-Vitreous hemorrhage',
  'Exudative retinal detachment',
  'CHRPE - Congenital hypertrophy of retinal pigment epithelium',
  'Retinal scar',
  'Advanced diabetic retinal disease',
  'Retinochoroidal coloboma',
  'Lattice retinal degeneration',
  'Pavingstone retinal degeneration',
  'Focal chorioretinal lesion',
  'Hemicentral retinal vein occlusion',
  'SECORD - Severe early childhood onset retinal dystrophy',
  'Retinal melanoma',
  'IRVAN (idiopathic retinal vasculitis, aneurysms, neuroretinitis) syndrome',
  'Horseshoe retinal tear without detachment',
  'PORN - progressive outer retinal necrosis',
  'Vitreoretinal tuft',
  'Lipaemia retinalis',
  'PED-Pigment epithelial detachment',
  'Retinal Metastasis',
  'Retinal Hamartoma',
  'Retinal IOFB',
  'Retinal Telangiectasia',
  'Retinal Capillary Hemangioma / Angioma Retinae',
  'Cone-rod retinal dystrophy',
  'Retinal arteriovenous malformation',
  'Macular retinal puckering',
  "Berlin's retinal edema",
  'Combined occlusion of retinal artery and retinal vein',
  'Retinal astrocytoma',
  'IJT-Idiopathic juxtafoveal telangiectasia',
  'DME-Diabetic macular edema',
  'Macular edema',
  'Congenital hyperplasia of retinal pigment epithelium',
  'Retinal round hole',
  'Retinal haemangioma',
  'Retinal lattice degeneration',
  'Retinal angiomatous proliferation',
  'Congenital hypertrophy of retinal pigment epithelium',
  'Preretinal fibrosis',
  'Cholesterol retinal embolus',
  'RAMSVPS - retinal arterial macroaneurysm with supravalvular pulmonic stenosis',
  'Retinal vitelliform deposits',
  'Retinal migraine',
  'SRNV-Subretinal neovascularisation',
  'Deep retinal hemorrhage',
  'Senile reticular retinal degeneration',
  'Bothnia retinal dystrophy',
  'RPED - Retinal pigment epithelial detachment',
  'Herpes zoster acute retinal necrosis',
  'Optic atrophy secondary to retinal disease',
  'Retinal nerve fiber bundle deficiency',
  'Abnormal retinal correspondence',
  'Retinal racemose hemangioma',
  "Krill's retinal pigment epitheliitis",
  'Primary non Hodgkin malignant lymphoma of vitreoretinal tract',
  'Reticular dystrophy of retinal pigment epithelium',
  'Retinal varices',
  'High myopia',
  'NPDR-Mild',
  'NPDR-Moderate',
  'NPDR-Severe',
  'CNVM-Choroidal neovascular membrane',
  'CME-Cystoid macular edema',
  'CSCR-Central serous chorioretinopathy',
  'Normal',
  'FTMH-Full thickness macular hole',
  'LMH-Lamellar macular hole',
  'ARMD-Age related macular degeneration',
];
