class FundusSection {
  const FundusSection({
    required this.key,
    required this.label,
    required this.options,
  });

  final String key;
  final String label;
  final List<String> options;
}

const fundusMediaOptions = [
  'Clear',
  'Cortex Drop',
  'Dislocated IOL in vitreous cavity',
  'Hazy (Descriptive option)',
  'Nucleus Drop',
  'PFCL with SOF',
  'Air filled (Descriptive option)',
  'SF6 filled (Descriptive option)',
  'C3F8 filled (Descriptive option)',
  'SOF',
  'Vitritis',
  'Other',
];

const fundusOpticDiscOptions = [
  "Bergmiester's papilla",
  'Collaterals',
  'Coloboma',
  'Colour (Descriptive option)',
  'Cup Disc ratio (Descriptive option)',
  'Disc pallor',
  'Drusen',
  'Fibrovascular proliferations',
  'Margins (Descriptive option)',
  'Melanocytoma',
  'Myelinated optic nerve head',
  'Myopic Disc',
  'Neovascularization',
  'Neuroretinal rim thinning/loss (Descriptive option)',
  'Normal',
  'Notching',
  'Oedema',
  'Optic disc haemorrhage',
  'Optic disc pit',
  'Peripapillary atrophy',
  'Shape (Descriptive)',
  'Size (Descriptive)',
  'Temporal pallor',
  'Tilted disc',
  'Vitreopapillary tractions',
  'Other',
];

const fundusVesselsOptions = [
  'Arteriolar attenuation',
  'Arteriosclerotic changes',
  'AV crossing changes',
  'Dilatation',
  'Neovascularization elsewhere (NVE)',
  'Normal',
  'Sclerotic',
  'Sheathed',
  'Tortuous',
  'Vascular occlusions ( Descriptive option)',
  'Other',
];

const fundusBackgroundOptions = [
  'Albinotic fundus',
  'Altered',
  'Angioid streaks',
  'ARMD',
  'Bony spicules (Decriptive option)',
  'BRAO',
  'BRVO',
  'Chorioretinal atrophic patches',
  'Chorioretinal degeneration',
  'Choroidal Detachment',
  'Choroidal Rupture',
  'Choroidal Tumours',
  'CHRPE',
  'CHRRPE',
  'Complete Vascularization',
  'Cotton Wool spots',
  'CRAO',
  'CRVO',
  'CSCR',
  'DR (Descriptive option)',
  'Drusen',
  'Exudates',
  'FEVR',
  'Gravitational tract',
  'Haemorrhage (Descriptive option)',
  'Hypertensive retinopathy',
  'Incomplete vascularization',
  'Microaneurysm',
  'Normal',
  'Pale fundus',
  'PAR',
  'PCV',
  'PED',
  'PEHCR',
  'Peripheral retinal degenerations ( Descriptive option)',
  'Polyp',
  'Posterior Staphyloma',
  'PRP laser marks',
  'PVD',
  'RAM',
  'RC Coloboma (Descriptive option)',
  'Retinal detachment (Descriptive option)',
  'Retinal haemangioblastoma',
  'Retinitis pigmentosa',
  'Retinoblastoma (Descriptive option)',
  'ROP (Descriptive option)',
  'Subretinal fluid',
  'Subretinal PFCL',
  'Tessellated',
  'Tractional Retinal Detachment (Descriptive option)',
  'Vasoproliferative tumours',
  'Other',
];

const fundusMaculaOptions = [
  'Absent',
  'Active CNVM',
  'Attached',
  "Bull's eye Maculopathy",
  'CI DME',
  'CME',
  'Detached',
  'Dull',
  'ERM',
  'Flecks',
  'Foveal hypoplasia',
  'Lamellar Macular Hole',
  'Macular TRVO',
  'MTM',
  'NCI DME',
  'Post PPV for Macular Hole',
  'Premacular Haemorrhage',
  'Present',
  'Pseudohole',
  'Retinoschisis',
  'RPE degeneration',
  'Scarred CNVM',
  'Stargardt disease',
  'Subfoveal PFCL',
  'Subretinal fibrosis',
  'Subretinal fluids',
  'Vitelliform lesions',
  'Other',
];

const fundusSections = [
  FundusSection(
    key: 'media',
    label: 'Media',
    options: fundusMediaOptions,
  ),
  FundusSection(
    key: 'optic_disc',
    label: 'Optic Disc',
    options: fundusOpticDiscOptions,
  ),
  FundusSection(
    key: 'vessels',
    label: 'Vessels',
    options: fundusVesselsOptions,
  ),
  FundusSection(
    key: 'background_retina',
    label: 'Background Retina',
    options: fundusBackgroundOptions,
  ),
  FundusSection(
    key: 'macula',
    label: 'Macula',
    options: fundusMaculaOptions,
  ),
];
