const surgicalLearningOptions = [
  'BIOM focusing',
  'Making a port',
  'Suturing',
  'Core Vitrectomy',
  'PVD induction',
  'Base Shaving Vitrectomy',
  'Fluid Air exchange',
  'Silicone oil removal',
  'Silicone oil removal with fluid air exchange',
  'Membrane peeling - bi manual technique',
  'Membrane peeling - unimanual technique',
  'Membrane peeling - with cutter',
  'ILM staining and peeling',
  'ERM staining and peeling',
  'Silicone oil injection',
  'Gas injection',
  'Intravitreal injection',
  'Intravitreal Ozurdex',
  'Intravitreal injection with gas tamponade',
  'Pneumoretinopexy',
  'SFIOL surgery steps - Conjunctival peritomy',
  'SFIOL surgery steps - Sclero-corneal tunnel',
  'SFIOL surgery steps - Scleral pockets',
  'SFIOL surgery steps - Core Vitrectomy',
  'SFIOL surgery steps - IOL insertion, haptic exteriorisation and tucking of haptics',
  'SFIOL surgery steps - IOL removal of dropped IOL',
  'SFIOL surgery steps - Parsplana lensectomy',
  'SFIOL surgery steps - Corneo-scleral suturing and conjunctival suturing',
  'Buckle Surgery - Conjunctival peritomy',
  'Buckle Surgery - Identifying and tagging extra ocular muscles',
  'Buckle Surgery - Suture/tunnel for 240 band and passing the band',
  'Buckle Surgery - Identifying and marking the break',
  'Buckle Surgery - Cryotherapy',
  'Buckle Surgery - Place the buckle at the point of break and suture',
  'Buckle Surgery - Tightening of buckle and band',
  'Buckle Surgery - Sutures for',
];
